name: nix ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  NIX_CONFIG: experimental-features = nix-command flakes

jobs:
  format:
    runs-on: codeberg-small
    container:
      image: nixos/nix:latest
    steps:
      - run: |
          git clone "${{ github.server_url }}/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"
      - run: nix run --inputs-from . nixpkgs#alejandra -- --check .

  flake-check:
    runs-on: codeberg-medium
    container:
      image: nixos/nix:latest
    steps:
      - run: |
          git clone "${{ github.server_url }}/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"
      - run: nix flake check
