name: nix formatter

on:
  push:
    branches: [ main master ]
  pull_request:
    branches: [ main master ]

jobs:
  alejandra-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: check formatting with alejandra
        run: nix shell nixpkgs#alejandra -c alejandra --check .
